# Generated by Django 3.2.15 on 2022-09-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20220918_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.pizzaitem')),
            ],
        ),
    ]
