# Generated by Django 3.2.15 on 2022-09-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_alter_orderitem_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='api_app.toppingitem'),
        ),
    ]
