# Generated by Django 3.2.15 on 2022-09-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_alter_orderitem_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='toppingitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='api_app.orderitem'),
        ),
    ]
