# Generated by Django 3.2.15 on 2022-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_auto_20220918_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(related_name='toppings', to='api_app.ToppingItem'),
        ),
    ]
